### ISSUE TITLE
Incorrectly specify the encoding

### ISSUE THREAD

**Issue by Barbaris2** [gignupg/Detect-File-Encoding-And-Language#1]
Hi, everyone!
I have a problem with the library. I am trying to determine the encoding of text documents. And I get the wrong result. My documents .doc and .docx with UTF-8 encoding and language Russian return the result: encoding = BIG5, language = Chinese.
Has anyone come across this? How to fix it?

I will be glad to good advice

**Comment by gignupg** [comment]
Thank you for reporting this issue! Can you send me the file?

**Comment by gignupg** [comment]
I did some testing and it turns out that supporting formats such as .doc and .docx would require a massive amount of extra work for me. So, it's not possible at the moment. I've updated the readme to let people know which formats are supported: https://github.com/gignupg/Detect-File-Encoding-and-Language#functionality
