### ISSUE TITLE
Issue in code base when detecting encoding from predefined array

### ISSUE THREAD

**Issue by polyakov84** [gignupg/Detect-File-Encoding-And-Language#9]
I've found issue when library tries to check already defined encoding matches element of predefined byteOrderMarkObject 

You're using include method for searching simple string in array of objects. Please see a screen.
<img width="684" alt="Screenshot 2022-09-09 at 09 13 25" src="https://user-images.githubusercontent.com/1419526/189284775-04f8496c-aaf1-4640-8e72-0bc5934aedf7.png">

**Comment by polyakov84** [comment]
Also as a feature request.
Please add possibility to skip language detection just encoding.
Thanks.

**Comment by polyakov84** [comment]
You could replace this line to the next and it will forks fine.
`if (!byteOrderMarkObject.find((el) => el.encoding === fileInfo.encoding)) {`

**Comment by gignupg** [comment]
Hey @polyakov84, thx for reporting this issue! 
It should be fixed now. I published a new version to NPM!

Regarding your feature request, I'm afraid the approach that this package uses to detect the encoding doesn't work without detecting the language first. Except of course when we detect the encoding via the byte order mark, but we can't rely on that alone, because it doesn't work 100% of the time.
